server:
  port: 80
spring:
  application:
    name: consul-consumer-order
  cloud:
    consul:
      # consul注册中心地址
      host: 192.168.1.3
      port: 8500
      discovery:
#        hostname: 127.0.0.1
        service-name: ${spring.application.name}